
import com.intellij.driver.sdk.invokeAction
import com.intellij.driver.sdk.ui.components.UiComponent.Companion.waitFound
import com.intellij.driver.sdk.ui.components.common.codeEditor
import com.intellij.driver.sdk.ui.components.common.ideFrame
import com.intellij.driver.sdk.ui.components.settings.settingsDialog
import com.intellij.ide.starter.driver.engine.runIdeWithDriver
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Test
import steps.ProjectPrep
import steps.ProjectSteps.createClassFromTemplate
import steps.SettingsSteps.createTemplate
import steps.SettingsSteps.deleteTemplate
import steps.SettingsSteps.modifyClassTemplate
import java.awt.event.KeyEvent
import kotlin.time.Duration.Companion.minutes


class SettingsEditorTestWithDriver {

    @Test
    fun createCustomTemplateAndGenerateClass() {

        val testContext = ProjectPrep.createTestContext()

        testContext.runIdeWithDriver().useDriverAndCloseIde {

            ideFrame {

                waitForIndicators(5.minutes)

                // Open Settings using main menu
                invokeAction("ShowSettings")

                // Work with Settings dialog
                settingsDialog {

                    createTemplate(
                        templateName = "TestTemplate",
                        templateContent = "public class \${NAME}  { " +
                                ""
                    )

                }
                waitForIndicators(1.minutes)

                createClassFromTemplate(
                    templateName = "TestTemplate",
                    className = "MyGeneratedClass"
                )

                // Verify generated content
                codeEditor().apply {
                    waitFound()

                    assertTrue(
                        text.contains("public class MyGeneratedClass"),
                        "Generated class content is incorrect"
                    )
                }
            }
        }
    }

    @Test
    fun modifyExistingClassTemplate() {

        val testContext = ProjectPrep.createTestContext()

        testContext.runIdeWithDriver().useDriverAndCloseIde {
            ideFrame {

                Thread.sleep(2000)

                invokeAction("ShowSettings")

                settingsDialog {
                    modifyClassTemplate()
                }

                createClassFromTemplate(
                    templateName = "Java Class",
                    className = "ModifiedTemplateClass"
                )

                codeEditor().apply {
                    assertTrue(
                        text.contains("// GENERATED BY TEST"),
                        "Modified template content was not generated"
                    )
                }
            }
        }
    }

    @Test
    fun deleteCustomTemplate() {
        val testContext = ProjectPrep.createTestContext()

        testContext.runIdeWithDriver().useDriverAndCloseIde {
            ideFrame {

                invokeAction("ShowSettings")

                settingsDialog {
                    createTemplate(
                        templateName = "TestTemplate",
                        templateContent = "public class \${NAME} {" +
                                ""
                    )
                }

                invokeAction("ShowSettings")

                settingsDialog {
                    deleteTemplate(templateName = "TestTemplate")
                }

                keyboard {
                    hotKey(KeyEvent.VK_ALT, KeyEvent.VK_INSERT)

                    typeText("TestTemplate")

                    enter()
                }

                Thread.sleep(1000)

                assertFalse(
                    x("//div[@accessiblename='TestTemplate']").present(),
                    "Deleted template is still available"
                )
            }
        }
    }
}


