package steps

import com.intellij.driver.sdk.ui.components.settings.SettingsDialogUiComponent
import com.intellij.driver.sdk.ui.xQuery

object SettingsSteps {

    private val EDITOR_TREE_SECTION =
        "Editor"

    private val FILE_AND_CODE_TEMPLATES =
        xQuery { byVisibleText("File and Code Templates") }

    private val CREATE_TEMPLATE =
        xQuery { byAccessibleName("Create Template") }

    private val TEMPLATE_LIST =
        xQuery { byType("javax.swing.JList") }

    private val TEMPLATE_NAME =
        xQuery { byAccessibleName("Name:") }

    private val EDITOR_TEXT_AREA =
        xQuery { byAccessibleName("Editor") }

    private val REMOVE_TEMPLATE =
        xQuery { byAccessibleName("Remove Template") }

    private val APPLY =
        xQuery { byAccessibleName("Apply") }

    private val OK =
        xQuery { byAccessibleName("OK") }

    fun SettingsDialogUiComponent.createTemplate(
        templateName: String, templateContent: String
    ) {
        openTreeSettingsSection(EDITOR_TREE_SECTION)

        x(FILE_AND_CODE_TEMPLATES).click()

        x(CREATE_TEMPLATE).click()

        x(TEMPLATE_NAME)

        keyboard {
            typeText(templateName)
        }

        x(EDITOR_TEXT_AREA).click()

        keyboard {

            hotKey(
                java.awt.event.KeyEvent.VK_CONTROL, java.awt.event.KeyEvent.VK_A
            )

            backspace()

            typeText(templateContent)

            enter()
        }

        x(APPLY).click()
        x(OK).click()

    }

    fun SettingsDialogUiComponent.modifyClassTemplate() {

        openTreeSettingsSection(EDITOR_TREE_SECTION)

        x(FILE_AND_CODE_TEMPLATES).click()

        x(TEMPLATE_LIST).click()

        keyboard {

            hotKey(java.awt.event.KeyEvent.VK_HOME)
            // Move to Class
            down()
            down()
        }


        x(EDITOR_TEXT_AREA).click()

        keyboard {

            hotKey(
                java.awt.event.KeyEvent.VK_CONTROL, java.awt.event.KeyEvent.VK_HOME
            )

            typeText("// GENERATED BY TEST")

            enter()
            enter()
        }

        x(APPLY).click()
        x(OK).click()
    }

    fun SettingsDialogUiComponent.deleteTemplate(templateName: String) {

        openTreeSettingsSection(EDITOR_TREE_SECTION)

        x(FILE_AND_CODE_TEMPLATES).click()

        // Focus template list
        x(TEMPLATE_LIST).click()

        keyboard {

            // Search by typing
            typeText(templateName)
            escape()

            Thread.sleep(500)

            // Delete template
            x(REMOVE_TEMPLATE).click()
        }

        x(APPLY).click()
        x(OK).click()
    }
}