package steps

import com.intellij.driver.sdk.ui.components.settings.SettingsDialogUiComponent

object SettingsSteps {

    private const val EDITOR_TREE_SECTION = "Editor"

    private const val FILE_AND_CODE_TEMPLATES =
        "//div[@text='File and Code Templates']"

    private const val CREATE_TEMPLATE =
        "//div[@accessiblename='Create Template']"

    private const val TEMPLATE_LIST =
        "//div[contains(@classhierarchy,'javax.swing.JList')]"

    private const val TEMPLATE_NAME =
        "//div[@accessiblename='Name:' and @class='javax.swing.JTextField']"

    private const val EDITOR_TEXT_AREA =
        "//div[@accessiblename='Editor']"

    private const val REMOVE_TEMPLATE =
        "//div[@accessiblename='Remove Template']"

    private const val APPLY =
        "//div[@accessiblename='Apply']"

    private const val OK =
        "//div[@accessiblename='OK']"

    fun SettingsDialogUiComponent.createTemplate(
        templateName: String, templateContent: String
    ) {
        openTreeSettingsSection(EDITOR_TREE_SECTION)

        x(FILE_AND_CODE_TEMPLATES).click()

        x(CREATE_TEMPLATE).click()

        x(TEMPLATE_NAME)

        keyboard {
            typeText(templateName)
        }

        x(EDITOR_TEXT_AREA).click()

        keyboard {

            hotKey(
                java.awt.event.KeyEvent.VK_CONTROL, java.awt.event.KeyEvent.VK_A
            )

            backspace()

            typeText(templateContent)

            enter()
        }

        x(APPLY).click()
        x(OK).click()

    }

    fun SettingsDialogUiComponent.modifyClassTemplate() {

        openTreeSettingsSection(EDITOR_TREE_SECTION)

        x(FILE_AND_CODE_TEMPLATES).click()

        x(TEMPLATE_LIST).click()

        keyboard {

            hotKey(java.awt.event.KeyEvent.VK_HOME)
            // Move to Class
            down()
            down()
        }


        x(EDITOR_TEXT_AREA).click()

        keyboard {

            hotKey(
                java.awt.event.KeyEvent.VK_CONTROL, java.awt.event.KeyEvent.VK_HOME
            )

            typeText("// GENERATED BY TEST")

            enter()
            enter()
        }

        x(APPLY).click()
        x(OK).click()
    }

    fun SettingsDialogUiComponent.deleteTemplate(templateName: String) {

        openTreeSettingsSection(EDITOR_TREE_SECTION)

        x(FILE_AND_CODE_TEMPLATES).click()

        // Focus template list
        x(TEMPLATE_LIST).click()

        keyboard {

            // Search by typing
            typeText(templateName)
            escape()

            Thread.sleep(500)

            // Delete template
            x(REMOVE_TEMPLATE).click()
        }

        x(APPLY).click()
        x(OK).click()
    }
}